#
# Makefile for the Altera device drivers.
#

obj-$(CONFIG_INTEL_S10_100GHIP) += intel_s10_100ghip.o
intel_s10_100ghip-objs := altera_s10_100ghip.o \
altera_s10_100ghip_debug.o altera_s10_100ghip_ethtool.o altera_s10_msgdma.o altera_s10_utils.o
